version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Run tests
          command: npm test || echo "No tests found, skipping"

      - run:
          name: Run the app and check output
          command: |
            node index.js &
            sleep 3
            curl -s http://localhost:3000 | grep "Hello World"
            pkill node

workflows:
  version: 2
  build:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold_for_approval:
          type: approval
  
      - deploy:
          requires:
            - hold_for_approval
